version: '3'
services:
  web-app:
    build:
      context: ./web-app
    ports:
      - 8080:80

  user-service:
    build: 
      context: ./user-service
    ports:
      - 3001:3001
    volumes:
      - .:/home/node/app
    environment:
      - API_URL=http://app:3001

